[project]
name = "tools"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
 "ipykernel>=7.2.0",
 "langchain>=1.2.15",
 "langchain-anthropic>=1.4.0",
 "langchain-community>=0.4.1",
 "langchain-llama-server",
 "langchain-mcp-adapters>=0.2.2",
 "langchain-openai>=1.1.12",
 "pytest>=9.0.3",
 "pytest-watch>=4.2.0",
 "rich>=14.3.3",
 "wikipedia>=1.4.0",
 "yapf>=0.43.0",
 "youtube-search>=2.2.0",
]

[tool.uv.sources]
langchain-llama-server = { path = "../../langchain-llama-server", editable = true }
langchain-mcp-adapters = { path = "../../../langchain-ai/langchain-mcp-adapters", editable = true }
